spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver
  cloud:
    config:
      enabled: false

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false