spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: task-service
          uri: lb://TASK-MICROSERVICE #host.docker.internal:task-microservice #
          predicates:
            - Path=/tasks/**
          filters:
            - StripPrefix=0
        - id: project-service
          uri: lb://PROJECT-MICROSERVICE
          predicates:
            - Path=/projects/**
          filters:
            - StripPrefix=0

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
