spring:
  datasource:
    url: jdbc:postgresql://projectsdb:5433/projectsdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=100,maximumSize=500,\
        expireAfterAccess=600s

  application:
    name: project-microservice

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.hbm2ddl: debug