server:
  port: 8082

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  application:
    name: notification-microservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/